### ISSUE TITLE
Does not work on TiddlyDesktop

### ISSUE THREAD

**Issue by thomhGeoCode** [tgrosinger/tw5-checklist#26]
I "installed" the plugin in my Wiki and it works fine in the browser (Chrome) but it does not work in TiddlyDesktop.

If I create a Tiddler with just:
[x] First Task
as content I receive the error message, when I try to close the tiddler ("confirm changes"):

Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read property '1' of undefined

I can close the error box and still save my wiki. Once I restart the wiki and try to open the tiddler with the task the same error message shows up again.

Any help?

**Comment by tgrosinger** [comment]
Hi thomhBonn,
I have never used TiddlyDesktop so I am not familiar with what problems might occur there that wouldn't occur otherwise. I will try to get to this issue, but it might be a trickier one.

**Comment by thomhGeoCode** [comment]
I noticed in the meantime that TiddlyDesktop is not longer supported. It might be a problem with the version of node.js implemented in the last version of TiddlyDesktop. So, do not worry about this one anymore.
