### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by TiddlyTweeter** [tgrosinger/tw5-checklist#30]
Ciao. [Documentation](https://grosinger.net/tw5-checklist/#%24%3A%2Fplugins%2Ftgrosinger%2Ftw5-checklist%2FUsage) shows this ...

![capture](https://cloud.githubusercontent.com/assets/28830541/26280097/dd97ffa6-3dc7-11e7-8e0e-732bca1f531b.PNG)

... but now it can be configured :-)

Best wishes
Josiah

**Comment by tgrosinger** [comment]
Oh, why did you close this? I don't think the issue has been resolved yet.

**Comment by TiddlyTweeter** [comment]
My bad. I thought it had been addressed.
