### ISSUE TITLE
COLOUR Coding Revisted

### ISSUE THREAD

**Issue by TiddlyTweeter** [tgrosinger/tw5-checklist#33]
I wanted to add more thoughts about COLOUR and push it a bit more.

> Thomas > 7 - Applying colours to items would pose problems: a) how would a user apply them? any interface addon or code one would have to know would make the tool more complicated b) as your words imply a colourful list would break the minimalism.
> 
> Josiah >> 7 - Keeping the minimalism but adding a congruent sense of differentiation between items. Use COLOUR. A limited colour pallet drop-down of say, 4 colours, // DELETE-> on the left next to each item <-DELETE//

_Thomas, I don't think colour would break minimalism at all. At the item level it would be a "useful visual differentiation with the lowest level of impact on the mechanics of the interface"._

How would you add colour? At the point of creation. Checklist items are not re-entrant so in the interface the mechanism could be a paintbrush instead of the pen. Hover on it and it would produce a drop-down of the colours available. So the interface looks the same as it is now, except the pen has become a brush.

The interface requirements can be minimal since creating Checklist items is a "one way ticket" ... i.e. you write and wikitext them on first entry. Anything more and you have to manually edit anyway.

_I'm not, of course, saying colour selection would be easy to do. I have no real grasp of what would be involved. But if doable without having to eat off your leg, its an enhancement that could be worth it, I think._

By way of example here is a clip of a specialist food list I created for my own use in a word processor that uses colour coding well to communicate to the shopper what to buy (green), what to be okay with (black) and what to try to avoid (red).

![capture](https://cloud.githubusercontent.com/assets/28830541/26585142/9054a844-454b-11e7-8646-4735aed7d409.PNG)

**Comment by tgrosinger** [comment]
You can already add color to list items the same way you can with any text in TiddlyWiki.

Try adding this as a list item

```
@@color:red;This has color!@@
```

**Comment by TiddlyTweeter** [comment]
Ciao Tony. Thank you for showing how easy that is.

I'm still slightly wondering how to keep the minimalism of Checklist AND enhance its utility. When I used your WikiText example I suddenly realised what my issue was. 

_Its having ways to enhance Checklist (if possible) without the user having to remember WikiText.

SO, my current suggestion shifts to CAN the input box be **set to remember history?** 

I mean that all previous strings entered are automatically recorded (maybe to a data Tiddler) and displayed in a drop-down? So, for instance, if a user started to type "@..." a dropdown would appear that shows all items that start "@..." They would click the specific item and the item would appear in the entry area for completion. 

_I have no idea if this is doable._

Ask if what I am getting at is unclear.

**Comment by tgrosinger** [comment]
I think that would definitely be possible, but we would definitely want that to be an off-by-default feature since it would be storing potentially lots of information invisibly.

Perhaps it could just store the most recent 500 or something, rather than everything forever. @TiddlyTweeter  could you move this suggestion into a new issue and perhaps close this one if you feel it is resolved?

Thank you
