### ISSUE TITLE
Thanks on version 0.0.14

### ISSUE THREAD

**Issue by TiddlyTweeter** [tgrosinger/tw5-checklist#37]
Thankyou @tgrosinger  & @telmiger for the update!

Its a step on from the last version. I've was able to recreate an old large Word template for Shopping in TW using Checklist in under an hour. FYI, here is a clip of part of the _printed output_ (I used "@ media print" to hide parts of the interface) ... 
![capture](https://user-images.githubusercontent.com/28830541/28442551-1c965bbc-6db1-11e7-83e1-1ff8944ce7b6.PNG)

The strike-through works correctly now. And having the delete function on the right is a good functional change.

The explicit option to NOT change the order on ticking "complete" is a very GOOD enhancement that will really help users like me me who create Checklists in a very precise order they want to preserve. 

I will comment separately with some suggestions for future versions.

This note may be closed once read.

Best wishes
Josiah

**Comment by telmiger** [comment]
Thank you @TiddlyTweeter for the feedback and the nice example!
Happy shopping,
Thomas

**Comment by tgrosinger** [comment]
Glad to hear the changes were improvements. Thanks to @telmiger for doing all the work.
