### ISSUE TITLE
The Intrusion of Buttons

### ISSUE THREAD

**Issue by TiddlyTweeter** [tgrosinger/tw5-checklist#39]
This is a visual design issue.

I personally don't like seeing this ... The _buttons circled in red_ I'd prefer they NOT be visible except when you hover on a line. 
![capture](https://user-images.githubusercontent.com/28830541/28443097-4c6363b4-6db4-11e7-9cc3-56775294a9b2.PNG)

Of course, you may feel most users need to see them all the time to understand the function of them.

I'd be happy enough with understanding what I can change in the CSS to ensure I only see the button on hover. 

But maybe it would work for everyone well without them being constantly visible?

Best wishes
Josiah

**Comment by telmiger** [comment]
Two reasons why these buttons have to be visible:

1. Access without a mouse: Users of tablets and phones have no mouse to hover – how should they become aware of hidden functions? Other people can’t or won’t use a mouse. Only visible buttons can be activated via keyboard.
2. New users will realise how things work when they **see** what is possible. Nobody wants to read a readme text first.

Of course we could try to style some elements less prominently and maybe make them **nearly** invisible.

Personally I would hide the _New list item …_ input field first. Sometimes a list is finished and does not need additional elements. Then it would be nice to use the pencil icon to make the input disappear/reappear.

**Comment by TiddlyTweeter** [comment]
@telmiger Let me put this in a Bauhaus Art way ... so long as I can TWEAK it so i don't see them UNLESS I need to I'll be happy.

I just don't know how to do that. I know how to do "visibility: hidden" on them. What I need is "visible: only-on-hover" .... maybe I made that CSS up  :-) ? But you get the idea. 

Josiah

**Comment by telmiger** [comment]
You are heading in the right direction, Josiah. For hiding I use
.classname { display: none }

then to show on hover
.classname:hover { display: unset }

Hope this helps for your personal optimisations!
-t

**Comment by TiddlyTweeter** [comment]
Tx Thomas. I will try it. 

Josiah

**Comment by TiddlyTweeter** [comment]
@telmiger wrote ... 
> Personally I would hide the New list item … input field first. Sometimes a list is finished and does not need additional elements. Then it would be nice to use the pencil icon to make the input disappear/reappear.

I been thinking more about this. I think that is a VERY good idea. _But why not hide ALL interface buttons at the same time? i.e. clicking on "pencil" also hides "-" and "recycle"?_

**Comment by tgrosinger** [comment]
I also agree that these buttons should stay. I have a plugin which adds keyboard shortcuts for everything, but I can't use it on things I can't see.

Closing this issue, but feel free to open another for future suggestions.
